version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flipkoro-api
    container_name: flipkoro-api
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      DB_HOST: 127.0.0.1
      DB_DATABASE: test_db
      DB_USERNAME: root
      DB_PASSWORD: password
      PURCHASE_CODE: 5915d718-ad31-4745-b756-4fe05c3d4ac4
      BUYER_USERNAME: Dutytaker
      SOFTWARE_ID: MzE0NDg1OTc=
      SOFTWARE_VERSION: 14.4
    # volumes:
    #   - ./:/var/www/html
    #   - ./public:/var/www/html/public
#     depends_on:
#       - db
#   db:
#     image: mysql:5.7
#     container_name: laravel-db
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: laravel
#       MYSQL_USER: laraveluser
#       MYSQL_PASSWORD: your_password
#       MYSQL_ROOT_PASSWORD: root_password
#     volumes:
#       - dbdata:/var/lib/mysql
# volumes:
#   dbdata:
